tried to fix the issue
SahilK-027/trinity-testimonials pull request #7
Opened 2023-03-01 15:33 UTC by Sumitkaranjkar

2023-03-01 16:23 UTC, SahilK-027 commented on index.html
>              <img class="student-img" src=https://avatars.githubusercontent.com/u/98700773?s=400&u=5b02ac4c23f43b4bcc7129f4da5a659c91515ad0&v=4>
Hey, src should go in quotes.
```html
<img class="student-img" src="https://avatars.githubusercontent.com/u/98700773?s=400&u=5b02ac4c23f43b4bcc7129f4da5a659c91515ad0&v=4">
```

2023-03-01 16:26 UTC, SahilK-027 requested changes
Add the link in double quotes and your code will work fine.

2023-03-01 16:37 UTC, SahilK-027 commented
And you don't need to close PR then make changes and open new PR again. Just do the suggested changes in your fork, give a proper commit message, and sync the fork, that's it. Your updations will be automatically added to the PR.

2023-03-02 17:45 UTC, Sumitkaranjkar commented
now you can merge thanks

2023-03-03 02:55 UTC, SahilK-027 approved these changes

2023-03-03 02:55 UTC, SahilK-027 commented
Thanks for the PR

2023-03-03 02:55 UTC, merged